services:
    app:
      build: .

      volumes:
        - .:/app
        - /app/node_modules

      ports:
        - "3000:3000"

      command: sh -c "npm run watch & npm run dev"

      restart: always
